---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Include dv.yml
    include_vars:
      file: vars/dv.yml

  - name: Include qa.yml
    include_vars:
      file: vars/qa.yml

  - debug:
      msg: "{{ var_dv }} and {{ var_qa }}"
